public enum TokenType {
    EOF, ERROR,
    INT, FLOAT, IF, ELSE, WHILE, PRINT, RETURN,
    IDENTIFIER, INTEGER,
    PLUS, MINUS, MULTIPLY, DIVIDE, ASSIGN,
    EQUAL, NOT_EQUAL, LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,
    SEMICOLON, LPAREN, RPAREN, LBRACE, RBRACE
}
